export const HEADER_CONFIG = {
    MOBILE_HEIGHT: 64,
    DASHBOARD_DESKTOP_HEIGHT: 92,
    DASHBOARD_DESKTOP_OFFSET_HEIGHT: 92 - 32,
    MAIN_DESKTOP_HEIGHT: 88
};

export const NAVBAR_CONFIG = {
    BASE_WIDTH: 260,
    DASHBOARD_COLLAPSE_WIDTH: 88,
    DASHBOARD_ITEM_ROOT_HEIGHT: 48,
    DASHBOARD_ITEM_SUB_HEIGHT: 40,
    DASHBOARD_ITEM_HORIZONTAL_HEIGHT: 32,
    DASHBOARD_WIDTH: 280
};

export const ICON_CONFIG = {
    NAVBAR_ITEM_HORIZONTAL: 20,
    NAVBAR_ITEM: 22
};
